name: Create Flatcar releases PR

on:
  workflow_dispatch:

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout flatcar-website repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install -r tools/release-scripts/requirements.txt

      - name: Run update-flatcar-versions script
        run: |
          ./update-flatcar-versions.sh

      - name: Commit changes
        run: |
          BRANCH=buildbot/release-$(date +%Y%m%d)
          git config --global user.name "Flatcar Buildbot"
          git config --global user.email "buildbot@flatcar-linux.org"
          git checkout -B "${BRANCH}"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 1
          fi
          BODY="data: Add new Flatcar releases

          $(git diff --staged --name-only --diff-filter=A data/releases/{alpha,beta,stable,lts} | sed -e 's:data/releases/:* :' -e 's:\.yml$::' -e 's:/: :g')"
          git commit --author "${GITHUB_ACTOR} <${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com>" --message "${BODY}"
          git push --force origin "${BRANCH}"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --fill \
            --title "data: Add new Flatcar releases $(date +%F)" \
            --reviewer "flatcar/flatcar-maintainers"
